lang: fr
theme: bulma-clean-theme

url: https://github.com/gorinje/craft-the-cv2

force_theme: light
permalink: pretty
lang: fr
theme_color: '#56817A'
fixed_navbar: top
show_logo: true

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
  projects:
    output: true
    layout: project
    image: https://via.placeholder.com/800x600
    show_sidebar: false

plugins:
  - jekyll-remote-include
  - jekyll-dotenv

env:
  gist_url: "{{ site.data.env.GIST_URL }}"
  owner_name: "{{ site.data.env.OWNER_NAME }}"